### PR TITLE
Cleanup refactor modularize and migrate typescript

### LINKED ISSUE #43: Cleanup, Refactor and Modularize the Code
The current implementation of the code in the repository consists of three JavaScript files: bot.js, summarizer.js, and surveyToText.js. These files are quite lengthy and would benefit from modularization and cleanup. This refactor would improve the codebase by enhancing readability, maintainability, and scalability.

### PR DESCRIPTION
**Pull request by berkingurcan**
1. Code cleaned
2. Modularized into two separate folders ```lib``` and ```commands```: 
Lib is for utility, helper and other functions. Commands is for handlers and command functions or any discord command related codes. Also created config, constants and and prompt files in order to use them easily.

3. Project, bot.js and their helpers in commands folder migrated to Typescript and added temporary types.
4. Refactored necessary variables.
5. Refactored imports bot.ts and commands into ```@commands``` for easier and good looking imports
6. Used [Redis Cloud](https://redis.io/) more fluent integration. And explained in readme.
7. Updated Readme.
8. Added necessary dependencies, test folder for further tests.
9. GPT Model changed into gpt-4-turbo

### CODE REVIEW

**Comment by es92** [comment]
Hey looks good! Can you confirm this is fully tested? There is a test discord linked in the readme I can give you access to if helpful for testing with multiple people aslo

**Comment by berkingurcan** [comment]
Yes it is done we checked things on devops side with @johnmarcou. Then I have pushed the changes also to this branch.
It is OK now but need to have .env.local file instead of .env file before running. 

I am currently in the testing discord channel but I think I tested all functionalities manually on my test server :)

**Comment by johnmarcou** [comment]
> Yes it is done we checked things on devops side with @johnmarcou. Then I have pushed the changes also to this branch. It is OK now but need to have .env.local file instead of .env file before running.
> 
> I am currently in the testing discord channel but I think I tested all functionalities manually on my test server :)

Yes, `Dockerfile` is building properly and `docker-compose` is starting the container properly too.
Note that we will have breaking change on the configuration (`REDIS_URL` becomes `REDIS_{HOST, PORT, PASSWORD}`).
That will produce a downtime on the `staging` environment, just the time we reconfigure the deployment configuration (`helm` chart) to use the new values.

**Comment by Smorci** [comment]
The helm chart changes have been implemented and deployed on the staging environment.

The MF DevOps team is ready to accept this change.

**Review by es92 — APPROVED** [review]

**Comment by berkingurcan** [comment]
This can be merged finally, https://github.com/MinaFoundation/gptSurveySummarizer/pull/56

**Review by johnmarcou — APPROVED** [review]
LGTM!

**Pull request merged**
